### ISSUE TITLE
Ios Simulator Zoom gesture not work

### ISSUE THREAD

**Issue by toffeantyri** [p-lr/MapComposeMP#13]
Gesture with two finger - zoom gesture.
Ios simulator can simulate it gesture by hold alt/opt button and slide mouse.

Zoom in MapComposeMP not work( 

I cant check it on physical device.

Xcode 15.1
Simulator runtime 17.2

**Comment by p-lr** [comment]
This is an issue with Compose multiplatform. I'll make and update of this dependency.

**Comment by p-lr** [comment]
I can confirm that zoom gestures are working in v.`1.9.4`
