### ISSUE TITLE
WasmJS target

### ISSUE THREAD

**Issue by stashymane** [p-lr/MapComposeMP#16]
Would be great to provide a wasmJs target.

**Comment by stashymane** [comment]
I've so far tried to copy-paste the desktop target to WASM, and it mostly compiles, except for one flaw: WASM lacks threading. The closest alternative would be web workers, which would (probably) require writing a separate webworker module, or just running it all on the main thread. Webworker support would require some changes to the base library in the form of more expect/actual.

**Comment by p-lr** [comment]
Interesting. If you manage to get it working, I would gladly accept a PR.
In the meantime, could you please make a PR for the updated dependencies and other gradle fixes?

**Comment by stashymane** [comment]
Working on it :)

**Comment by atesahmet0** [comment]
This would be a nice feature. Thanks for your time.

> Working on it :)
