### ISSUE TITLE
Blinking when navigating to map with Compose Navigation?

### ISSUE THREAD

**Issue by JakkeJ** [p-lr/MapComposeMP#4]
Seems to be blinking everytime I am navigating to the map for some reason, not sure why this would happen.
I am using Navigation from Compose Multiplatform.

`@Composable
fun MapScreen(
    modifier: Modifier = Modifier,
    navController: NavController
) {
    val viewModel = koinInject<MapViewModel>()
    MapUI(
        modifier,
        state = viewModel.state
    )`

Pretty basic setup, the tileStreamProvider gets the data from SQLDelight unless there is nothing in the database, then it will load it from a remote tileserver.

**Comment by p-lr** [comment]
Do you reproduce the issue using the demo app?

**Comment by JakkeJ** [comment]
> Do you reproduce the issue using the demo app?

I haven't tried, I am thinking it could be Compose Navigation, weirdly enough it does NOT happen in iOS, only Android... I am relying on Compose Navigation to work with it though, as I need navigation and I don't have time to redo it with Decompose or something else, it is used in a bachelor thesis, which is due next month.

I'll let this sit and see if I can figure it out tomorrow, been at it for 9 hours now! :)

**Comment by p-lr** [comment]
If you can reproduce this in a fork of the demo app, I'll be able to investigate.

**Comment by JakkeJ** [comment]
It was the reloadTiles method. On non-MP I had to run it in my composable, else it wouldn't show me the tiles that had to be downloaded until I moved the map, only the cached ones in SQLDelight.

But on MP it works without it just fine, so that is what caused the blinking on Android. It is weird it didn't blink on iOS though, but I won't complain, it works!

**Comment by JakkeJ** [comment]
I'll just close it, since it is sorted out! :)

**Comment by p-lr** [comment]
Glad you sorted this out!
