### ISSUE TITLE
Getting exception on TileCanvasThread - Problem decoding into existing bitmap

### ISSUE THREAD

**Issue by JakkeJ** [p-lr/MapComposeMP#5]
Is this a known bug, or is there something I am doing wrong somewhere? I thought I caught it in my else block in the code below, becuase it stopped happening, or so I thought, but it randomly happened when I zoomed out very far (on a real device, didn't happen on emulator, yet), and once when I disconnected my phone while running the app (for testing GPS).

```
class MapRepositoryImpl (
    private val db: SARDatabase,
    private val tileDownloader: TileDownloader,
    private val scope: CoroutineScope
) : MapRepository {
    override fun getTile(row: Long, col: Long, zoomLvl: Long): Flow<RawSource?> = flow {
        val log = logging("MapRepository DB")
        val tileData = db.tileQueries.selectTile(row, col, zoomLvl).executeAsOneOrNull()

        val buffer = Buffer()
        buffer.write(tileData?.tile_data ?: byteArrayOf())
        if (tileData != null) {
            emit(buffer)
        } else {
            log.d { "Downloading from web" }
            tileDownloader.downloadTile(row, col, zoomLvl).let { dataPair ->
                val tileStream = dataPair.first
                val bytes: ByteArray? = dataPair.second
                if (tileStream != null) {
                    emit(tileStream)
                    scope.launch {
                        if (bytes != null) {
                            try {
                                db.tileQueries.insertTile(row, col, zoomLvl, bytes)
                            } catch (e: Exception) {
                                log.e{ "Attempt to insert duplicate tile.: $e" }
                            }
                        }
                    }
                } else {
                    log.e { "Failed to download tile" }
                    emit(null)
                }
            }
        }
    }
}
```

Any tips as to why this happens and which steps I need to take to avoid this are very much appreciated! :)

**Comment by p-lr** [comment]
Could you also post the stacktrace?

**Comment by JakkeJ** [comment]
Sorry I don't have it stored, I have to drop every small issue like this these days unless it happens a lot, we got a hard deadline on this (bachelor's thesis), and it hasn't happened since. I have limited the zoom to minimum of 8, it seemed to happen when I zoomed out far and fast, which there is no need for as this is a search and rescue app anyways. I test this app 6-10 hours per day in emulator, simulator and real devices, so it is very rare.

I do have a question though, probably not appropriate in here right now, but if not I'll create a separate issue on it. When I rotate the map, and I take that rotation and add it to a marker, the marker moves around on the map. This is on a real device with me standing still, so the location isn't changing.

**Comment by p-lr** [comment]
When this happens again, the stacktrace will be helpful.

Regarding your issue with markers, you can create a separate issue. However this is most probably due to wrong values of `relativeOffset` when calling [addMarker](https://github.com/p-lr/MapComposeMP/blob/62a0975976f250208abb62e5add7736eea538bd0/library/src/commonMain/kotlin/ovh/plrapps/mapcompose/api/MarkerApi.kt#L48) api. Default value is (-0.5f, -1f) so that the fixed point of a pin marker is at the bottom center. A marker which should be centered should use (-0.5f, -0.5f).

**Comment by JakkeJ** [comment]
> When this happens again, the stacktrace will be helpful.
> 
> Regarding your issue with markers, you can create a separate issue. However this is most probably due to wrong values of `relativeOffset` when calling [addMarker](https://github.com/p-lr/MapComposeMP/blob/62a0975976f250208abb62e5add7736eea538bd0/library/src/commonMain/kotlin/ovh/plrapps/mapcompose/api/MarkerApi.kt#L48) api. Default value is (-0.5f, -1f) so that the fixed point of a pin marker is at the bottom center. A marker which should be centered should use (-0.5f, -0.5f).

I will get a stacktrace if it happens again! I can say it happened on line 132 in some file, where it started with something like val image = or val images = , not sure if that helps you at all but, who knows! :)

As for the marker, I will try that out! Thanks!
