### ISSUE TITLE
Location status bar icon blinks when rotating map and asking for the map rotation value in composable

### ISSUE THREAD

**Issue by JakkeJ** [p-lr/MapComposeMP#6]
I can't see any reason for it to happen, I am using Moko Geo 0.18 to get location, not that I think that is relevant, because it happens when I don't ask for location at all, just have the right things initialised in the ViewModel to be able to get the location, and rotate the map. I need the map rotation to get the proper heading with data from the magnetometer/accelerometer and all that.

It seems like it blinks when it recomposes, but I can't get why it would happen when I am not using location actively.

If anyone has succeeded with this, let me know!

**Comment by p-lr** [comment]
It doesn't sound like an issue with the library. Without for details about relevant parts of your code, it's hard to tell.
