### ISSUE TITLE
Coroutine Scope in MapState references Dispatchers.Main

### ISSUE THREAD

**Issue by lsrom** [p-lr/MapComposeMP#7]
Currently, `ovh.plrapps.mapcompose.ui.state.MapState`  creates coroutine scope like this: `CoroutineScope(SupervisorJob() + Dispatchers.Main)` but `Dispatchers.Main` is not present on desktop so it forces dependency on some coroutine library that provides it, which `kotlinx.coroutines.Dispatchers` documentation tells me should javafx, but that doesn't work for me. All this could be avoided if the `MapState` took coroutine scope as it's parameter, avoiding any direct references to `Dispatchers.Main`. I haven't tested it, but it should resolve the issue.

I am willing to submit pull request if you think this solution is acceptable. I am just trying to run this in multiplatform project and this seems to be a show stopper for now.

This is the error I get btw:

`Module with the Main dispatcher is missing. Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android' and ensure it has the same version as 'kotlinx-coroutines-core'`

**Comment by p-lr** [comment]
This makes sense. When I tested the desktop version, it runned fine for me. Perhaps this is because the desktop demo app  has a dependency on ktor-android (which probably brings the Main dispatcher).

Another way to fix this issue may be to use `MainUIDispatcher` from `org.jetbrains.skiko` on desktop. What do you think?

**Comment by lsrom** [comment]
Imho, the less dependencies the better. I personally would prefer just a parameter I can do whatever with. Maybe just javadoc with example how to setup if people want to use some kind of Main dispatcher would be enough?

**Comment by p-lr** [comment]
I agree, however I'm not suggesting to add a new dependency for desktop since skiko is already a dependency of MapComposeMP.
Also, the library is _designed_ to do some operations in the same thread as the one used by the compose framework for draw operations. Allowing those operations to run on a different thread might have unattended consequences.

**Comment by lsrom** [comment]
If thats the case than it sounds fine. I'm not too familiar with the code so I don't know what might break. Should I open pull request with this change then?

**Comment by p-lr** [comment]
I'm thinking about an expect/actual mechanism to get the "main" dispatcher, depending on the platform. I believe android would be the only one using `Main`. A PR would be welcome, thanks!

**Comment by lsrom** [comment]
I did a bit of research and I don't think `MainUIDispatcher` is the way to go. This thread basically says it's a bad idea: https://github.com/JetBrains/compose-multiplatform/issues/1943 and I can't even get it to import in the project. And it's Swing dependency, thats bad imho. 

I suggest either making the scope an argument of the `MapState` as I said before, or making the scope in `MapState` an interface and implement it on each supported platform where android can have `Dispatchers.Main`. It's not working without it, you were right about that. Still haven't tested on desktop.

**Comment by p-lr** [comment]
Alright. Now I'm curious to find out which Dispatcher is used on desktop by Compose for draw operations.
If the library can use this dispatcher, this should be the one used.

**Comment by p-lr** [comment]
Alternatively, we can experiment how the library behaves with a used provided Dispatcher, as you suggest. In the future, Compose draw operations won't be tied  to single thread, so it's best to adapt ahead of time.

**Comment by lsrom** [comment]
If I add the parameter to the MapState and pass the same coroutine scope as is currently there, it should work with no problem on mobile and once I add it to my test desktop app, I can submit any potential fixes for desktop. Would that be fine? The lib might be working on desktop until I make fixes for it.

**Comment by lsrom** [comment]
Also a quick question, do I need to do more than `implementation("org.jetbrains.skiko:skiko:0.8.4")` in my demo app to make this work? I'm getting `java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/ui/graphics/SkiaBackedPaint_skikoKt;` and I'M not sure what else but adding the dependency I should do? Is it possible its not working because I'm including the lib as a jar directly? Built from desktopJar gradle task.
